### Register user
# @name Register user
# @assert response.statusCode == 201
POST {{base.url}}/api/auth/register
Content-Type: application/json

{
  "username": "testuser",
  "email": "text@example.com",
  "password": "correct-horse-battery"
}

### Invalid Registration
# @name Invalid Registration
# @assert response.statusCode == 400
POST {{base.url}}/api/auth/register
Content-Type: application/json

{
  "username": "x",
  "email": "not-an-email-lol",
  "password": "short"
}

### Duplicate registration
# @name Duplicates registration
POST {{base.url}}/api/auth/register
Content-Type: application/json

{
  "username": "testuser",
  "email": "text@example.com",
  "password": "correct-horse-battery"
}

### Login user (Valid Creds)
# @name Login user (Valid creds)
# @assert response.statusCode == 200
POST {{base.url}}/api/auth/login
Content-Type: application/json

{
  "email": "text@example.com",
  "password": "correct-horse-battery"
}

### Login user (Invalid Creds)
# @name Login user (Invalid Creds)
# @assert response.statusCode == 401
POST {{base.url}}/api/auth/login
Content-Type: application/json

{
  "email": "text@example.com",
  "password": "wrong-pass"
}

### Login user (Unknown email)
# @name Login user (Unknown email)
# @assert response.statusCode == 401
POST {{base.url}}/api/auth/login
Content-Type: application/json

{
  "email": "does-not-exist@example.com",
  "password": "correct-horse-battery"
}

### Login user (Invalid payload)
# @name Login user (Invalid payload)
# @assert response.statusCode == 400
POST {{base.url}}/api/auth/login
Content-Type: application/json

{
  "email": "not-an-email",
  "password": "short"
}

### Refresh token - valid
# @name Refresh token (valid)
# @assert response.statusCode == 200
POST {{base.url}}/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": "w5BeYaRBppXI_aE3uFs7U_5n4F7yhC1M1Bzp2swPiYU"
}